version: '3.8'

services:
  compiler-gui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: compiler-visualizer
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  compiler-gui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: compiler-visualizer-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev
